Check for unref before usage
inikulin/time-limit-promise pull request #3
Opened 2018-06-19 07:13 UTC by leahciMic

Browsers do not support `unref()`

2018-06-19 10:57 UTC, inikulin requested changes
Thank you for the contribution. Can you leave a comment in the code about why we need this check please?

2018-06-21 01:41 UTC, leahciMic commented
@inikulin No problems at all, sorry for the delay in adding the comment

2018-06-21 10:35 UTC, inikulin commented
Thanks!

2018-06-21 10:35 UTC, merged

2018-06-21 10:39 UTC, inikulin commented
Published as 1.0.4